trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 2023/01-try-mono-lib/turbo/*
variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
  - stage: build
    jobs:
    - job: build_job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: |
           npm | "$(Agent.OS)"
          path: $(npm_config_cache)

      - task: Npm@1
        inputs:
          command: 'ci'
          workingDir: '2023/01-try-mono-lib/turbo'

      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '2023/01-try-mono-lib/turbo'
          customCommand: 'lint'