trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 2023/03-monolib-deploy/*

pool:
  vmImage: ubuntu-latest

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
       npm | "$(Agent.OS)"
    path: $(npm_config_cache)
  displayName: Cache npm

- script: npm ci
- script: npm run build:lg
  env:
    BACKFILL_CACHE_PROVIDER: $(BACKFILL_CACHE_PROVIDER)
    BACKFILL_CACHE_PROVIDER_OPTIONS: $(BACKFILL_CACHE_PROVIDER_OPTIONS)
    LAGE_WRITE_REMOTE_CACHE: $(LAGE_WRITE_REMOTE_CACHE)