CREATE TABLE [dbo].[ToDo]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Description] NVARCHAR(255) NOT NULL,
    [Status] NVARCHAR(15) NOT NULL DEFAULT 'incompleted',
    [AddDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
    [UpdateDate] DATETIME2 NOT NULL DEFAULT GETDATE()
)
