# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 202301-try-mono-lib-nx

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '2023/01-try-mono-lib/nx/**'
      - '.github/workflows/2023-01-try-mono-lib-nx.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './2023/01-try-mono-lib/nx/'
    strategy:
      matrix:
        node-version: [18.10.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: './2023/01-try-mono-lib/nx/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - uses: nrwl/nx-set-shas@v3
      with:
        working-directory: './2023/01-try-mono-lib/nx/'
    - run: npm ci
    - run: npm run test:ci
    - run: npm run build:ci