# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 202303-monolib-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '2023/03-monolib-deploy/**'
      - '.github/workflows/2023-03-monolib-deploy.yml'

env:
  BACKFILL_CACHE_PROVIDER: azure-blob
  BACKFILL_CACHE_PROVIDER_OPTIONS: ${{ secrets.BACKFILL_CACHE_PROVIDER_OPTIONS }}
  LAGE_WRITE_REMOTE_CACHE: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: './2023/03-monolib-deploy/'
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://npm.pkg.github.com/
    - run: npm ci
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: './2023/03-monolib-deploy/node_modules'
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm run lint:lg
    - run: npm run test:lg
    - run: npm run build:lg
      # env:
      #   BACKFILL_CACHE_PROVIDER: azure-blob
      #   BACKFILL_CACHE_PROVIDER_OPTIONS: ${{ secrets.BACKFILL_CACHE_PROVIDER_OPTIONS }}
      #   LAGE_WRITE_REMOTE_CACHE: true
    - name: commit and push
      run: |
        git config user.email github-actions@github.com
        git config user.name github-actions
        npm run publish:bb
      env:
        NPM_AUTHTOKEN: ${{secrets.PACKAGE_PAT}}
        GITHUB_TOKENL: ${{secrets.GITHUB_TOKEN}}