# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 2023-10-mpt-ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '2023/10-playwright-testing/**'
      - '.github/workflows/2023-10-mpt-ci.yml'
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './2023/10-playwright-testing/'
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/sql-action@v2.2
      with:
        connection-string: ${{ secrets.DATABASE_CONNECTION_STRING }}
        path: './2023/10-playwright-testing/database/PlaywrightTesting.Database/Scripts/*.sql'

    - run: ls
    - run: cd e2e && npm ci && npm run test:mpt
      env:
        TARGET_URL: https://polite-forest-0c123db00.3.azurestaticapps.net
        PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN}}
        PLAYWRIGHT_SERVICE_URL: ${{secrets.PLAYWRIGHT_SERVICE_URL}}

    - name: Upload to blob storage
      if: always()
      uses: azure/CLI@v1
      with:
        inlineScript: |
          ls
          az storage blob upload-batch -s ./2023/10-playwright-testing/e2e/playwright-report/ --account-name stdotnetlab202310 --auth-mode key -d '$web' --overwrite true